In [1]:
# Run this program on your local python
# interpreter, provided you have installed
# the required libraries.
  
# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report
  

In [4]:
# Function importing Dataset
balance_data = pd.read_csv('Dataset-1.csv')


In [5]:
print(balance_data.describe())

                  2           2.1             0      0.1             6  \
count  35951.000000  35951.000000  35951.000000  35951.0  35951.000000   
mean       2.997358      2.096576     11.500320      0.0     15.680510   
std        1.999045      0.731426      6.922113      0.0      8.795799   
min        0.000000      0.000000      0.000000      0.0      1.000000   
25%        1.000000      2.000000      6.000000      0.0      8.000000   
50%        3.000000      2.000000     12.000000      0.0     16.000000   
75%        5.000000      3.000000     17.500000      0.0     23.000000   
max        6.000000      3.000000     23.000000      0.0     31.000000   

                  1           1.1          2016            85          74.8  \
count  35951.000000  35951.000000  35951.000000  35951.000000  35951.000000   
mean       6.504826      2.498707   2017.966677     80.786265     71.277138   
std        3.427310      1.111449      1.249913     12.648272     12.439201   
min        1.0000

In [6]:
balance_data.head

<bound method NDFrame.head of        2  2.1   0  0.1  6  1  1.1  2016  85  74.8  ...  89.4  65  21  9.5  \
0      2    2   1    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
1      2    2   2    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
2      2    2   3    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
3      2    2   4    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
4      2    2   5    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
...   ..  ...  ..  ... .. ..  ...   ...  ..   ...  ...   ...  ..  ..  ...   
35946  1    2  19    0  7  7    3  2020  93  84.5  ...  76.6  53  15  6.1   
35947  1    2  20    0  7  7    3  2020  93  84.5  ...  76.6  53  15  6.1   
35948  1    2  21    0  7  7    3  2020  93  84.5  ...  76.6  53  15  6.1   
35949  1    2  22    0  7  7    3  2020  93  84.5  ...  76.6  53  15  6.1   
35950  1    2  23    0  7  7    3  2020  93  84.5  ...  76.6  53  15  6.1   

       0.2  29.8  29.8.1  29.7  0.3  1.057  


In [7]:
# Printing the dataswet shape
print("Dataset Length: ", len(balance_data))
print ("Dataset Shape: ", balance_data.shape)

Dataset Length:  35951
Dataset Shape:  (35951, 25)


In [8]:
# Printing the dataset obseravtions
print ("Dataset: ",balance_data.head())
print(balance_data)

Dataset:     2  2.1  0  0.1  6  1  1.1  2016  85  74.8  ...  89.4  65  21  9.5  0.2  \
0  2    2  1    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
1  2    2  2    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
2  2    2  3    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
3  2    2  4    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
4  2    2  5    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   

   29.8  29.8.1  29.7  0.3  1.057  
0  29.8    29.8  29.7  0.0  1.171  
1  29.8    29.8  29.7  0.0  0.560  
2  29.8    29.8  29.7  0.0  0.828  
3  29.8    29.8  29.7  0.0  0.932  
4  29.8    29.8  29.7  0.0  0.333  

[5 rows x 25 columns]
       2  2.1   0  0.1  6  1  1.1  2016  85  74.8  ...  89.4  65  21  9.5  \
0      2    2   1    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
1      2    2   2    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5   
2      2    2   3    0  6  1    1  2016  85  74.8  ...  8

In [10]:
# Separating the target variable
X = balance_data.values[:, :-1]
Y = balance_data.values[:, ]

In [11]:
 # Splitting the dataset into train and test
X_train, X_test, y_train, y_test = train_test_split( 
X, Y, test_size = 0.3, random_state = 100)
X, Y, X_train, X_test, y_train, y_test

(array([[ 2. ,  2. ,  1. , ..., 29.8, 29.7,  0. ],
        [ 2. ,  2. ,  2. , ..., 29.8, 29.7,  0. ],
        [ 2. ,  2. ,  3. , ..., 29.8, 29.7,  0. ],
        ...,
        [ 1. ,  2. , 21. , ..., 29.8, 29.8,  0. ],
        [ 1. ,  2. , 22. , ..., 29.8, 29.8,  0. ],
        [ 1. ,  2. , 23. , ..., 29.8, 29.8,  0. ]]),
 array([1.171, 0.56 , 0.828, ..., 2.138, 2.199, 1.809]),
 array([[5.00e+00, 3.00e+00, 2.00e+01, ..., 3.01e+01, 3.00e+01, 0.00e+00],
        [3.00e+00, 2.00e+00, 9.00e+00, ..., 2.98e+01, 2.98e+01, 0.00e+00],
        [1.00e+00, 2.00e+00, 1.40e+01, ..., 2.99e+01, 2.98e+01, 0.00e+00],
        ...,
        [2.00e+00, 2.00e+00, 8.00e+00, ..., 2.97e+01, 2.97e+01, 2.37e+00],
        [3.00e+00, 2.00e+00, 0.00e+00, ..., 3.00e+01, 2.99e+01, 0.00e+00],
        [3.00e+00, 2.00e+00, 1.20e+01, ..., 2.97e+01, 2.96e+01, 1.00e-02]]),
 array([[2.00e+00, 2.00e+00, 1.70e+01, ..., 2.99e+01, 2.98e+01, 9.00e-02],
        [5.00e+00, 3.00e+00, 6.00e+00, ..., 2.99e+01, 2.98e+01, 0.00e+00],
       

In [12]:
# Creating the classifier object
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,max_depth=3, min_samples_leaf=5)

In [1]:
# Performing training
clf_gini.fit(X_train, y_train)
clf_gini

NameError: name 'clf_gini' is not defined

In [11]:
 # Decision tree with entropy
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth = 3, min_samples_leaf = 5)
  

In [12]:
 # Performing training
clf_entropy.fit(X_train, y_train)
clf_entropy

DecisionTreeClassifier(criterion='entropy', max_depth=3, min_samples_leaf=5,
                       random_state=100)

In [13]:
# Predicton on test with giniIndex
y_pred = clf_entropy.predict(X_test)
print("Predicted values:")
print(y_pred)
y_pred

Predicted values:
['R' 'L' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'L'
 'R' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R'
 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R'
 'R' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'L'
 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R'
 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'L'
 'R' 'L' 'R' 'R' 'L' 'R' 'L' 'L' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L'
 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'R' 'R'
 'R' 'R' 'R' 'L' 'R' 'L' 'R' 'R']


array(['R', 'L', 'R', 'L', 'L', 'L', 'L', 'L', 'R', 'R', 'R', 'L', 'L',
       'R', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'R', 'R', 'L', 'R', 'R',
       'R', 'R', 'R', 'L', 'L', 'L', 'R', 'L', 'R', 'R', 'R', 'L', 'R',
       'L', 'L', 'L', 'R', 'L', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'R',
       'R', 'R', 'R', 'R', 'R', 'R', 'L', 'L', 'R', 'L', 'R', 'L', 'L',
       'R', 'R', 'R', 'R', 'L', 'R', 'L', 'R', 'L', 'L', 'R', 'L', 'R',
       'R', 'R', 'R', 'R', 'L', 'L', 'R', 'R', 'R', 'L', 'R', 'L', 'R',
       'R', 'L', 'L', 'R', 'R', 'R', 'L', 'L', 'R', 'L', 'L', 'L', 'R',
       'L', 'R', 'R', 'R', 'L', 'L', 'R', 'R', 'R', 'R', 'L', 'R', 'R',
       'R', 'R', 'R', 'L', 'L', 'R', 'R', 'L', 'L', 'R', 'L', 'R', 'R',
       'L', 'R', 'L', 'L', 'R', 'R', 'R', 'R', 'R', 'R', 'L', 'R', 'R',
       'R', 'R', 'L', 'R', 'L', 'L', 'R', 'R', 'R', 'L', 'R', 'L', 'R',
       'L', 'R', 'L', 'R', 'R', 'L', 'R', 'L', 'R', 'R', 'R', 'R', 'R',
       'R', 'R', 'L', 'R', 'R', 'R', 'L', 'L', 'R', 'R', 'R', 'R

In [14]:
print("Confusion Matrix: ", confusion_matrix(y_test, y_pred))

Confusion Matrix:  [[ 0  6  8]
 [ 0 53 38]
 [ 0 11 72]]


In [15]:
print ("Accuracy : ",accuracy_score(y_test,y_pred)*100)

Accuracy :  66.48936170212765


In [16]:
print("Report : ",classification_report(y_test, y_pred))

Report :                precision    recall  f1-score   support

           B       0.00      0.00      0.00        14
           L       0.76      0.58      0.66        91
           R       0.61      0.87      0.72        83

    accuracy                           0.66       188
   macro avg       0.46      0.48      0.46       188
weighted avg       0.64      0.66      0.63       188



C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif

In [17]:
# Building Phase
data = importdata()
#X, Y, X_train, X_test, y_train, y_test = split_dataset(data)
clf_gini = train_using_gini(X_train, X_test, y_train)
clf_entropy = tarin_using_entropy(X_train, X_test, y_train)

NameError: name 'importdata' is not defined

In [1]:
# Run this program on your local python
# interpreter, provided you have installed
# the required libraries.

# Importing the required packages
import numpy as np
import pandas as pd
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

# Function importing Dataset
def importdata():
	balance_data = pd.read_csv(
'https://archive.ics.uci.edu/ml/machine-learning-'+
'databases/balance-scale/balance-scale.data',
	sep= ',', header = None)
	
	# Printing the dataswet shape
	print ("Dataset Length: ", len(balance_data))
	print ("Dataset Shape: ", balance_data.shape)
	
	# Printing the dataset obseravtions
	print ("Dataset: ",balance_data.head())
	return balance_data

# Function to split the dataset
def splitdataset(balance_data):

	# Separating the target variable
	X = balance_data.values[:, 1:5]
	Y = balance_data.values[:, 0]

	# Splitting the dataset into train and test
	X_train, X_test, y_train, y_test = train_test_split(
	X, Y, test_size = 0.3, random_state = 100)
	
	return X, Y, X_train, X_test, y_train, y_test
	
# Function to perform training with giniIndex.
def train_using_gini(X_train, X_test, y_train):

	# Creating the classifier object
	clf_gini = DecisionTreeClassifier(criterion = "gini",
			random_state = 100,max_depth=3, min_samples_leaf=5)

	# Performing training
	clf_gini.fit(X_train, y_train)
	return clf_gini
	
# Function to perform training with entropy.
def tarin_using_entropy(X_train, X_test, y_train):

	# Decision tree with entropy
	clf_entropy = DecisionTreeClassifier(
			criterion = "entropy", random_state = 100,
			max_depth = 3, min_samples_leaf = 5)

	# Performing training
	clf_entropy.fit(X_train, y_train)
	return clf_entropy


# Function to make predictions
def prediction(X_test, clf_object):

	# Predicton on test with giniIndex
	y_pred = clf_object.predict(X_test)
	print("Predicted values:")
	print(y_pred)
	return y_pred
	
# Function to calculate accuracy
def cal_accuracy(y_test, y_pred):
	
	print("Confusion Matrix: ",
		confusion_matrix(y_test, y_pred))
	
	print ("Accuracy : ",
	accuracy_score(y_test,y_pred)*100)
	
	print("Report : ",
	classification_report(y_test, y_pred))

# Driver code
def main():
	
	# Building Phase
	data = importdata()
	X, Y, X_train, X_test, y_train, y_test = splitdataset(data)
	clf_gini = train_using_gini(X_train, X_test, y_train)
	clf_entropy = tarin_using_entropy(X_train, X_test, y_train)
	
	# Operational Phase
	print("Results Using Gini Index:")
	
	# Prediction using gini
	y_pred_gini = prediction(X_test, clf_gini)
	cal_accuracy(y_test, y_pred_gini)
	
	print("Results Using Entropy:")
	# Prediction using entropy
	y_pred_entropy = prediction(X_test, clf_entropy)
	cal_accuracy(y_test, y_pred_entropy)
	
	
# Calling main function
if __name__=="__main__":
	main()


Dataset Length:  625
Dataset Shape:  (625, 5)
Dataset:     0  1  2  3  4
0  B  1  1  1  1
1  R  1  1  1  2
2  R  1  1  1  3
3  R  1  1  1  4
4  R  1  1  1  5
Results Using Gini Index:
Predicted values:
['R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'L'
 'L' 'R' 'L' 'R' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L' 'R' 'L' 'L' 'L'
 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'R' 'L' 'R'
 'R' 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R' 'L' 'R' 'L'
 'R' 'R' 'L' 'L' 'L' 'R' 'R' 'L' 'L' 'L' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'R'
 'R' 'L' 'R' 'L' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L'
 'L' 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R'
 'L' 'L' 'R' 'L' 'L' 'R' 'L' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'R' 'R'
 'L' 'L' 'R' 'R' 'R' 'R' 'L' 'R' 'R' 'R' 'L' 'R' 'L' 'L' 'L' 'L' 'R' 'R'
 'L' 'R' 'R' 'L' 'L' 'R' 'R' 'R']
Confusion Matrix:  [[ 0  6  7]
 [ 

C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\UCA\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modif