In [2]:
# Importing the required modules for linear regression using python
import matplotlib.pyplot as plt
import pandas as pd


In [3]:
# Importing the dataset
import numpy as np
import pandas as pd
dataset = pd.read_csv('Dataset-1.csv')


In [4]:
dataset.head()

2  2.1  0  0.1  6  1  1.1  2016  85  74.8  ...  89.4  65  21  9.5  0.2  \
0  2    2  1    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
1  2    2  2    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
2  2    2  3    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
3  2    2  4    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   
4  2    2  5    0  6  1    1  2016  85  74.8  ...  89.4  65  21  9.5    0   

   29.8  29.8.1  29.7  0.3  1.057  
0  29.8    29.8  29.7  0.0  1.171  
1  29.8    29.8  29.7  0.0  0.560  
2  29.8    29.8  29.7  0.0  0.828  
3  29.8    29.8  29.7  0.0  0.932  
4  29.8    29.8  29.7  0.0  0.333  

[5 rows x 25 columns]

In [21]:
#get a copy of dataset exclude last column
#slicing the data , Taking the 
#input_data = dataset.iloc[:, :-1].copy() all the columns except the last column, dropping the last columm
input = np.array(dataset.iloc[:, 2].values) # taking the second column as input, since it is linear regression and we neeed only on input and one output 
output = np.array(dataset.iloc[:, -1].values) #droping all the columns and taking the last column as output 

In [22]:
input , output 

(array([ 1,  2,  3, ..., 21, 22, 23], dtype=int64),
 array([1.171, 0.56 , 0.828, ..., 2.138, 2.199, 1.809]))

In [23]:
# Splitting the dataset into the Training data set and Testing data set
from sklearn.model_selection import train_test_split
# 30% data for testing, random state 1
X_train, X_test, y_train, y_test = train_test_split(input, output, train_size=.7, random_state=1)
#printing the splitted output values
print("training output values: \n",y_train)
print("Testing output values:\n",y_test)

training output values: 
 [0.919 0.256 0.289 ... 0.492 0.338 0.25 ]
Testing output values:
 [0.365 0.539 0.347 ... 0.181 0.759 0.231]


In [24]:
X_train = X_train.reshape(-1, 1)
X_test = X_test.reshape(-1, 1)


In [25]:
# Importing linear regression form sklear
from sklearn.linear_model import LinearRegression
# initializing the algorithm
regressor = LinearRegression()
# Fitting Simple Linear Regression to the Training set
regressor.fit(X_train, y_train)
# Predicting the Test set results
y_pred = regressor.predict(X_test)
y_pred

array([0.79759722, 0.75878357, 1.03047909, ..., 0.99166545, 0.56471534,
       0.9528518 ])

In [26]:
from sklearn.metrics import mean_squared_error, mean_squared_error
from sklearn.metrics import mean_absolute_error
# Assuming y_train and y_pred are the train and predicted labels, respectively
MSE = mean_squared_error(y_test, y_pred)
RMSE = mean_squared_error(y_test, y_pred, squared=False)
MAE = mean_absolute_error(y_test, y_pred)

In [27]:
MSE, RMSE , MAE

(0.737388192948193, 0.858713102816181, 0.6259451019704397)

# accuracy_score and linear regression 
Accuracy score is generally used to evaluate the performance of a classification model, where the predicted outputs are categorical. For continuous data, accuracy score might not be the most appropriate measure to use.

If we have continuous data and a corresponding set of true continuous values, we can use various measures to evaluate the performance of a model that predicts continuous values. Some common measures used for regression models are:

Mean Squared Error (MSE): calculates the average squared difference between the predicted and true values.

Root Mean Squared Error (RMSE): calculates the square root of the MSE, which gives an estimate of the average distance between the predicted and true values.

Mean Absolute Error (MAE): calculates the average absolute difference between the predicted and true values.

R-squared (R²): measures the proportion of variation in the dependent variable that is explained by the independent variables.

These measures can provide a better evaluation of the performance of a model that predicts continuous values than accuracy score.


In [28]:
# # importing the accuracy score
# from sklearn.metrics import accuracy_score
# # accuracy
# print(accuracy_score(y_test, y_pred))
# from sklearn.metrics import classification_report
# print(classification_report(y_test, y_pred))